name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push request event for the master branch
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    # Our previously created self-hosted runner
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ["6.0.x"]
        os: ["win", "linux"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Construct publish output directory
        run: echo '::set-output name=PUBLISH_OUTPUT::./release/${{ matrix.os }}'
        id: publish-output-directory

      - name: Publish
        run: dotnet publish --self-contained true -c Release --os ${{ matrix.os }} --output ${{ steps.publish-output-directory.outputs.PUBLISH_OUTPUT }}
        
      - name: Upload release (Windows)
        uses: svenstaro/upload-release-action@2.2.1
        if: ${{ matrix.os == 'win' }}
        with:
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.publish-output-directory.outputs.PUBLISH_OUTPUT }}/UnityPacker.exe
          asset_name: UnityPacker.exe
          tag: latest
        
      - name: Upload release (Linux)
        uses: svenstaro/upload-release-action@2.2.1
        if: ${{ matrix.os == 'linux' }}
        with:
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.publish-output-directory.outputs.PUBLISH_OUTPUT }}/UnityPacker
          asset_name: UnityPacker
          tag: latest